[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "EAScheduler"
dynamic = ["version", "readme"]
description = "Easy async scheduling with a nice interface"
authors = [
    { name = "spaceman_spiff" },
]
keywords = [
    "scheduler",
    "asyncio",
]
requires-python = ">=3.10"
dependencies = [
    "whenever==0.9.3",
    "astral==3.2",
    "holidays==0.85",
    "typing_extensions",
]
license = "EUPL-1.2"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
Homepage = "https://github.com/spacemanspiff2007/eascheduler"
Documentation = "https://eascheduler.readthedocs.io/"
GitHub = "https://github.com/spacemanspiff2007/eascheduler"

[project.optional-dependencies]
test = [
    "pytest==9.0.1",
    "pytest-asyncio==1.3.0",
    "tzlocal==5.3.1",
]
tools = [
    "ruff==0.14.5",
    "pur==7.3.3",
    "autotyping==24.9.0",
]


[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[tool.setuptools.package-data]
eascheduler = ["py.typed"]

[tool.setuptools.dynamic]
version = { attr = "eascheduler.__version__.__version__" }
readme = { file = ["readme.md"], content-type = "text/markdown" }
